name: use proselint to polish markdown texts

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:

  check_lint_on_markdown:
    name: check markdown lint

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: update repository
        run: sudo add-apt-repository universe
      
      - name: install proselint
        run: sudo apt install python3-proselint

      - name: run proselint
        continue-on-error: true
        run: proselint *.md >suggestions.md 2>&1

      - name: PR commit with file
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: suggestions.md
